/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmer_Native */

#ifndef _Included_org_wasmer_Native
#define _Included_org_wasmer_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmer_Native
 * Method:    nativePanic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wasmer_Native_nativePanic
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
