name: Dynamic libs

on:
  push:
    branches:
      - '**'

jobs:
  publish_dlibs:
    name: Publish the dynamic libraries
    strategy:
      matrix:
        platform:
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: darwin-arm64
            lib_name: libwasmer_jni.dylib

          - os: macos-latest
            target: x86_64-apple-darwin
            arch: darwin-amd64
            lib_name: libwasmer_jni.dylib

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: linux-amd64
            lib_name: libwasmer_jni.so

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: win32-amd64
            lib_name: wasmer_jni.dll

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Create the dynamic libs
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup target add ${{ matrix.platform.target }}
          cargo build --release --target=${{ matrix.platform.target }}

      - name: Upload the dynamic libs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.arch }}
          path: ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.lib_name }}
          retention-days: 7
          overwrite: true
