name: Dynamic libs

on: [push]

jobs:
  publish_dlibs:
    name: Publish the dynamic libraries
    strategy:
      matrix:
        platform:
          - os_name: macos
            os: macos-latest
            target: aarch64-apple-darwin

          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os_name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - os_name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Create the dynamic libs
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          make build-rust-all-targets
          ls

      - name: Get release info
        id: get_release_info
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}